[wokwi]
version = 1
firmware = 'artifacts/build/bme280_read_i2c.ino.hex'
elf = 'artifacts/build/bme280_read_i2c.ino.elf'
vcdFile = 'artifacts/logic/wokwi.vcd'

[[chip]]
name = 'bme280'
binary = 'chips/bme280.chip.wasm'
